theme: jekyll-theme-cayman

title: 'The EMV Standard: Break, Fix, Verify'
description: 'David Basin, Ralf Sasse, and Jorge Toro'

show_dowloads: false

github:
  is_project_page: false

header_btns:
  - <a href="https://arxiv.org/pdf/2006.08249" class="btn"><i class="fa fa-file-pdf-o"></i> Full paper</a>
  - <a href="https://github.com/EMVrace/EMVerify" class="btn"><i class="fa fa-github"></i> Tamarin models</a>
  - <a href="https://youtu.be/JyUsMLxCCt8" class="btn"><i class="fa fa-youtube-play"></i> Attack demo</a>
