theme: jekyll-theme-cayman

title: "The EMV Standard: Break, Fix, Verify"
description: David Basin, Ralf Sasse, and Jorge Toro | ETH Zürich

show_dowloads: false

github:
  is_project_page: false
  owner_name: Jorge Toro
  owner_url: https://jorgetp.github.io

header_btns:
  - <a href="https://arxiv.org/pdf/2006.08249" class="btn"><i class="fa fa-file-pdf-o"></i> Preprint on arxiv</a>
  - <a href="https://github.com/EMVrace/EMVerify" class="btn"><i class="fa fa-github"></i> Tamarin models</a>
  - <a href="https://youtu.be/JyUsMLxCCt8" class="btn"><i class="fa fa-youtube-play"></i> Demo video</a>
