theme: jekyll-theme-cayman

title: 'The EMV Standard: Break, Fix, Verify'
description: 'David Basin, Ralf Sasse, and Jorge Toro'

show_dowloads: false

github:
  is_project_page: false

header_btns:
  - <a href="https://arxiv.org/pdf/2006.08249.pdf" class="btn"><i class="fa fa-file-pdf-o"></i> PIN bypass for Visa</a>
  - <a href="https://jorgetp.github.io/assets/files/papers/USENIX21.pdf" class="btn"><i class="fa fa-file-pdf-o"></i> PIN bypass for Mastercard</a>
  #- <a href="https://github.com/EMVrace/EMVerify" class="btn"><i class="fa fa-github"></i> Get Tamarin models</a>
  #- <a href="https://youtu.be/JyUsMLxCCt8" class="btn"><i class="fa fa-youtube-play"></i> Watch demo video</a>
