theme: jekyll-theme-cayman

title: The EMV Standard
description: Break, Fix, Verify

show_dowloads: false

header_btn:
  text: View Tamarin models
  url: https://github.com/EMVrace/EMVerify

github:
  is_project_page: false